export type Product = {
  id: number;
  name: string;
  price: number;
  image: string;
  // images: string[];
  rating: number;
  category: string;
  badge?: "NEW" | "BESTSELLER" | "VEGAN";
  description: string;
  stock?: number;
};

export const products: Product[] = [
  {
    id: 1,
    name: "Rose Glow Lipstick",
    price: 25,
    image: "/1.jpg",
  //   images: [
  //   "/1.jpg",
  //   "/1-2.jpg",
  //   "/1-3.jpg",
  //   "/1-4.jpg",
  // ],
    rating: 4.8,
    category: "Makeup",
    badge: "BESTSELLER",
    description: "A soft lipstick with a beautiful natural glow.",
  },
  {
    id: 2,
    name: "Hydrating Face Serum",
    price: 30,
    image: "/2.jpg",
    rating: 5,
    category: "Skin Care",
    badge: "NEW",
    description: "A lightweight serum for a fresh, hydrated feel.",
  },
  {
    id: 3,
    name: "Silky Hair Shampoo",
    price: 20,
    image: "/3.jpg",
    rating: 4.6,
    category: "Hair Care",
    badge: "BESTSELLER",
    description: "A gentle shampoo for smooth, refreshed hair.",
  },
  {
    id: 4,
    name: "Soft Glow Foundation",
    price: 35,
    image: "/4.jpg",
    rating: 4.7,
    category: "Makeup",
    badge: "NEW",
    description: "A lightweight foundation with a natural radiant finish.",
  },
  {
    id: 5,
    name: "Daily Moisturizer",
    price: 28,
    image: "/5.jpg",
    rating: 4.5,
    category: "Skin Care",
    badge: "VEGAN",
    description: "A nourishing moisturizer for everyday use.",
  },
  {
    id: 6,
    name: "Nourishing Hair Mask",
    price: 32,
    image: "/6.jpg",
    rating: 4.7,
    category: "Hair Care",
    badge: "NEW",
    description: "A rich mask for smooth and nourished-looking hair.",
  },
  {
    id: 7,
    name: "Velvet Rose Blush",
    price: 24,
    image: "/7.jpg",
    rating: 4.8,
    category: "Makeup",
    badge: "BESTSELLER",
    description: "A soft blush for a naturally rosy finish.",
  },
  {
    id: 8,
    name: "Gentle Face Cleanser",
    price: 22,
    image: "/8.jpg",
    rating: 4.6,
    category: "Skin Care",
    badge: "VEGAN",
    description: "A gentle cleanser for a clean and refreshed feel.",
  },
  {
    id: 9,
    name: "Repair Conditioner",
    price: 26,
    image: "/9.jpg",
    rating: 4.4,
    category: "Hair Care",
    description: "A nourishing conditioner for soft, smooth hair.",
  },
  {
    id: 10,
    name: "Nude Eyeshadow Palette",
    price: 38,
    image: "/10.jpg",
    rating: 4.9,
    category: "Makeup",
    badge: "NEW",
    description: "Elegant neutral shades for effortless everyday looks.",
  },
  {
    id: 11,
    name: "Rose Face Mist",
    price: 27,
    image: "/11.jpg",
    rating: 4.7,
    category: "Skin Care",
    badge: "VEGAN",
    description: "A refreshing mist for a soft, hydrated feeling.",
  },
  {
    id: 12,
    name: "Nourishing Hair Oil",
    price: 29,
    image: "/12.jpg",
    rating: 4.5,
    category: "Hair Care",
    badge: "BESTSELLER",
    description: "A lightweight oil for a nourishing hair routine.",
  },
  {
    id: 13,
    name: "Peach Glow Lip Tint",
    price: 23,
    image: "/13.jpg",
    rating: 4.7,
    category: "Makeup",
    badge: "NEW",
    description:
      "A lightweight lip tint with a soft and natural peachy finish.",
  },
  {
    id: 14,
    name: "Luminous Concealer",
    price: 29,
    image: "/4.jpg",
    rating: 4.8,
    category: "Makeup",
    badge: "BESTSELLER",
    description:
      "A creamy concealer that gives smooth and natural-looking coverage.",
  },
  {
    id: 15,
    name: "Soft Matte Lip Gloss",
    price: 21,
    image: "/5.jpg",
    rating: 4.5,
    category: "Makeup",
    description: "A comfortable lip gloss with a soft matte finish.",
  },
  {
    id: 16,
    name: "Vitamin C Brightening Serum",
    price: 34,
    image: "/6.jpg",
    rating: 4.9,
    category: "Skin Care",
    badge: "BESTSELLER",
    description:
      "A refreshing serum designed to support a smooth and radiant-looking complexion.",
  },
  {
    id: 17,
    name: "Gentle Foaming Cleanser",
    price: 24,
    image: "/7.jpg",
    rating: 4.6,
    category: "Skin Care",
    badge: "NEW",
    description:
      "A gentle foaming cleanser for a fresh and comfortable skincare routine.",
  },
  {
    id: 18,
    name: "Overnight Face Cream",
    price: 36,
    image: "/8.jpg",
    rating: 4.8,
    category: "Skin Care",
    badge: "VEGAN",
    description: "A rich overnight cream for soft and nourished-looking skin.",
  },
  {
    id: 19,
    name: "Repair Hair Serum",
    price: 27,
    image: "/9.jpg",
    rating: 4.7,
    category: "Hair Care",
    badge: "NEW",
    description:
      "A lightweight hair serum for smooth and refreshed-looking hair.",
  },
  {
    id: 20,
    name: "Scalp Care Shampoo",
    price: 25,
    image: "/2.jpg",
    rating: 4.5,
    category: "Hair Care",
    description: "A gentle shampoo created for a clean and refreshed scalp.",
  },
  {
    id: 21,
    name: "Silky Hair Conditioner",
    price: 28,
    image: "/1.jpg",
    rating: 4.8,
    category: "Hair Care",
    badge: "BESTSELLER",
    description:
      "A nourishing conditioner for soft, smooth and manageable hair.",
  },
  {
    id: 22,
    name: "Rosy Cheek Blush",
    price: 26,
    image: "/2.jpg",
    rating: 4.7,
    category: "Makeup",
    badge: "NEW",
    description: "A silky blush that adds a naturally fresh rosy finish.",
  },
  {
    id: 23,
    name: "Hydra Balance Toner",
    price: 22,
    image: "/3.jpg",
    rating: 4.6,
    category: "Skin Care",
    badge: "VEGAN",
    description:
      "A refreshing toner that leaves skin feeling balanced and hydrated.",
  },
  {
    id: 24,
    name: "Nourishing Hair Treatment",
    price: 33,
    image: "/4.jpg",
    rating: 4.9,
    category: "Hair Care",
    badge: "BESTSELLER",
    description:
      "A rich treatment designed to leave hair feeling soft and nourished.",
  },
  {
    id: 25,
    name: "Liquid Eyeliner",
    price: 21,
    image: "/5.jpg",
    rating: 4.7,
    category: "Makeup",
    badge: "NEW",
    description: "A smooth liquid eyeliner for precise and defined looks.",
  },
  {
    id: 26,
    name: "Peach Lip Gloss",
    price: 23,
    image: "/2.jpg",
    rating: 4.6,
    category: "Makeup",
    badge: "BESTSELLER",
    description: "A glossy lip finish with a soft peachy touch.",
  },
  {
    id: 27,
    name: "Silk Touch Concealer",
    price: 29,
    image: "/7.jpg",
    rating: 4.8,
    category: "Makeup",
    description: "A lightweight concealer for a smooth natural finish.",
  },
  {
    id: 28,
    name: "Vitamin C Serum",
    price: 34,
    image: "/8.jpg",
    rating: 4.9,
    category: "Skin Care",
    badge: "BESTSELLER",
    description:
      "A refreshing serum designed for a bright and healthy-looking complexion.",
  },
  {
    id: 29,
    name: "Overnight Face Cream",
    price: 31,
    image: "/9.jpg",
    rating: 4.7,
    category: "Skin Care",
    badge: "NEW",
    description: "A rich overnight cream for a soft and moisturized feel.",
  },
  {
    id: 30,
    name: "Gentle Exfoliating Scrub",
    price: 26,
    image: "/3.jpg",
    rating: 4.5,
    category: "Skin Care",
    badge: "VEGAN",
    description:
      "A gentle facial scrub for a fresh and smooth-looking complexion.",
  },
  {
    id: 31,
    name: "Keratin Hair Serum",
    price: 30,
    image: "/1.jpg",
    rating: 4.8,
    category: "Hair Care",
    badge: "NEW",
    description: "A lightweight serum for smooth and manageable-looking hair.",
  },
  {
    id: 32,
    name: "Deep Repair Hair Mask",
    price: 33,
    image: "/2.jpg",
    rating: 4.7,
    category: "Hair Care",
    badge: "BESTSELLER",
    description: "A nourishing treatment for soft and healthy-looking hair.",
  },
  {
    id: 33,
    name: "Rosemary Hair Tonic",
    price: 28,
    image: "/3.jpg",
    rating: 4.6,
    category: "Hair Care",
    badge: "VEGAN",
    description:
      "A refreshing hair tonic for an easy everyday hair-care routine.",
  },
  {
    id: 34,
    name: "Soft Matte Lip Cream",
    price: 22,
    image: "/4.jpg",
    rating: 4.8,
    category: "Makeup",
    badge: "BESTSELLER",
    description: "A comfortable lip cream with a soft matte finish.",
  },
  {
    id: 35,
    name: "Aloe Hydration Gel",
    price: 25,
    image: "/5.jpg",
    rating: 4.7,
    category: "Skin Care",
    badge: "VEGAN",
    description:
      "A lightweight gel that leaves skin feeling fresh and hydrated.",
  },
  {
    id: 36,
    name: "Smooth & Shine Hair Oil",
    price: 29,
    image: "/6.jpg",
    rating: 4.5,
    category: "Hair Care",
    description:
      "A lightweight hair oil for a smooth and naturally shiny finish.",
  },
];

